name: Auto Commit Bot Updates

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main  # Change this if needed

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Pull and Commit Changes
        run: |
          git config --global user.name "botnyaaan"
          git config --global user.email "bot@example.com"
          git pull origin main
          git add .
          git commit -m "Automated update from bot"
          git push origin main
